### ISSUE TITLE
BasicSpawnSelect - HUD icons disappearing

### ISSUE THREAD

**Issue by LOWZONEDAYZ** [Krypton91/BasicSpawnSelect#2]
Hello Krypton91,

would like to report an actual issue with the mod BasicSpawnSelct

After choosing the spawn location and the BasicSpawnSelect window closes and teleported the player, the HUD completely disappears
All HUD icon´s/Symbols are gone
The normal solutions, like jumping, using ESC or just simple waiting (~10min test) do unfortunately not help
Looking for a explanation or maybe even a solution, i found that in the steam workshop mod, someone else described this problems, in your comments.

Would it be possible, that you take a look on this matter?
Thank you and best greetings LC

**Comment by Krypton91** [comment]
Hey i dont have this issue with a vanilla server and the mod!, maybe we can take a look  to it! :) Just hit me up in discord!

**Comment by LOWZONEDAYZ** [comment]
You won't believe how great it sounds that it's working for you!
That gives me hope to get it right
Thank you for your response!
Will set my test server completely to standard and try again, should it than work, will try it out on the LIVE server too
You made my day, hearing its working! Thank you
Hope i get it to work too and pin point whats the reason for the mentioned issue
Will write you in Discord afterwards and report how its going or coming back on your offer for help :)
regards LC

**Comment by LOWZONEDAYZ** [comment]
SOLVED

For everyone finding his way here:

It was not an issue caused by BasicSpawnSelection, but using this mod togheter with the VPPAdminTools mod and using the KILL COMMAND in VPP caused the HUD to disappear.
As far as i know, this only happens if both mods are used togheter.
Also, as only admins should be able to use the KILL COMMAND, it does not have any impact on normal players
Every respawn reason, besides the KILL COMMAND, does not let your HUD disappear

Workaround: 
After using the kill command and the player respawned and his HUD is missing -> teleport the player once and his HUD reappears

Using BasicSpawnSelection alone/without VPP works flawlessly
